---

name: Packer

on:
  push:
    #paths:
    #  - 03.packer/*

jobs:
  packer:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: azure-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve Secrets from HashiCorp Vault
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          #Shared Runner needs public facing IP of HCP Vault        
          url: https://hcp-vault-cluster-public-vault-e5830e3d.85b50f4b.z1.hashicorp.cloud:8200
          exportToken: true
          namespace: admin
          method: jwt
          role: github-actions
          secrets: |
            cloud-secrets/data/tfc-secret TFC_TOKEN | TFC_TOKEN ;
            azure/creds/dev client_id | ARM_CLIENT_ID ;
            azure/creds/dev client_secret | ARM_CLIENT_SECRET 

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
          
